package style
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF895100)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDCBC)
val md_theme_light_onPrimaryContainer = Color(0xFF2C1700)
val md_theme_light_secondary = Color(0xFF725A42)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFEDDBE)
val md_theme_light_onSecondaryContainer = Color(0xFF291805)
val md_theme_light_tertiary = Color(0xFF57633B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDAE8B5)
val md_theme_light_onTertiaryContainer = Color(0xFF151F01)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF1DFD0)
val md_theme_light_onSurfaceVariant = Color(0xFF50453A)
val md_theme_light_outline = Color(0xFF837568)
val md_theme_light_inverseOnSurface = Color(0xFFFAEFE7)
val md_theme_light_inverseSurface = Color(0xFF352F2B)
val md_theme_light_inversePrimary = Color(0xFFFFB86B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF895100)
val md_theme_light_outlineVariant = Color(0xFFD5C3B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB86B)
val md_theme_dark_onPrimary = Color(0xFF492900)
val md_theme_dark_primaryContainer = Color(0xFF683D00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCBC)
val md_theme_dark_secondary = Color(0xFFE1C1A3)
val md_theme_dark_onSecondary = Color(0xFF402C18)
val md_theme_dark_secondaryContainer = Color(0xFF58432C)
val md_theme_dark_onSecondaryContainer = Color(0xFFFEDDBE)
val md_theme_dark_tertiary = Color(0xFFBECC9B)
val md_theme_dark_onTertiary = Color(0xFF293411)
val md_theme_dark_tertiaryContainer = Color(0xFF3F4B25)
val md_theme_dark_onTertiaryContainer = Color(0xFFDAE8B5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEBE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEBE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF50453A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C3B5)
val md_theme_dark_outline = Color(0xFF9D8E81)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEBE1D9)
val md_theme_dark_inversePrimary = Color(0xFF895100)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB86B)
val md_theme_dark_outlineVariant = Color(0xFF50453A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFBD7A28)


val Green = Color(0xFF228B22)
val LightGreen = Green.copy(alpha = 0.7f)

val Yellow = Color(0xFFF2BE22)
val LightYellow = Yellow.copy(alpha = 0.7f)
